### ISSUE TITLE
Bug: Null KeyError

### ISSUE THREAD

**Issue by hbryant3** [kubinka0505/iFunny-Captions#15]
# Additional description

---

## `iFunny-Captions` Version 3.6

Running batch file and adding gif produces a KeyError. I assume it's to do with FFmpeg and other being assigned null value in Config.

### Console Log:
```bash
C:\Users\htemp\AppData\Local\Programs\Python\Python310\iFunny-Captions>python __init__.pyw -t "" -i "" -p
C:\Users\htemp\AppData\Local\Programs\Python\Python310\iFunny-Captions\__init__.pyw:28: DeprecationWarning: 'emoji.UNICODE_EMOJI_ENGLISH' is deprecated and will be removed in version 2.0.0. Use 'emoji.EMOJI_DATA' instead.
To hide this warning, pin/downgrade the package to 'emoji~=1.6.3'
  from emoji import emojize, demojize, UNICODE_EMOJI_ENGLISH
> iFunny-Captions 3.6 (02.01.2022)

Set up utils...
Traceback (most recent call last):
  File "C:\Users\htemp\AppData\Local\Programs\Python\Python310\iFunny-Captions\__init__.pyw", line 88, in <module>
    exec(open_("Packages_Location/FFmpeg"))
  File "<string>", line 15, in <module>
KeyError: None
```

**Comment by kubinka0505** [comment]
Yes, the packages selection through `Config.json` will be removed in the next release.

**Comment by hbryant3** [comment]
I've also noticed, now that I got it working, that sometimes when making a gif, it'll cut off the text? Should I change the wrapping of the text to stop that?
